<?php
/**
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @copyright   Copyright (c) 2015 Weboffice UG (haftungsbeschränkt) (http://www.Weboffice.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<select id="<?php echo $this->getId() ?>" name="<?php echo $this->getName() ?>" class="<?php echo $this->getClass() ?>" title="">
    <?php foreach ($this->getOptions() as $_value => $_option): ?>
        <?php if (isset($_option['is_group'])): ?>
            <?php if (isset($_option['is_close'])): ?>
                </optgroup>
            <?php else: ?>
                <optgroup label="<?php echo $_option['label'] ?>" style="<?php echo isset($_option['style']) ? $_option['style'] : ''; ?>">
            <?php endif; ?>
        <?php else: ?>
          <option value="<?php echo $_value ?>" style="<?php echo isset($_option['style']) ? $_option['style'] : ''; ?>">
              <?php echo $_option['label'] ?>
          </option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
