<?php 
     $enable = $this->getEnable();
     if (!$enable) {
         return;
     }
     $id = $this->getPixelId();
?>
<?php
$order_id = Mage::getSingleton('checkout/session')->getLastOrderId();
if (!$order_id || intval($order_id) < 1) {
    //Failsafe for bad order id
    return;
}
/** @var Mage_Sales_Model_Order $order */
$order = Mage::getModel('sales/order')->load($order_id);
$grand_total = round($order->getGrandTotal(), 2);
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
?>
<!-- Facebook Conversion Code for Conversions -->
<script>(function() {
        var _fbq = window._fbq || (window._fbq = []);
        if (!_fbq.loaded) {
            var fbds = document.createElement('script');
            fbds.async = true;
            fbds.src = '//connect.facebook.net/en_US/fbds.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(fbds, s);
            _fbq.loaded = true;
        }
    })();
    window._fbq = window._fbq || [];
    window._fbq.push(['track', '<?php echo $id ?>', {'value':'<?php echo $grand_total ?>','currency':'<?php echo $currency_code ?>'}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=<?php echo $id ?>&amp;cd[value]=<?php echo $grand_total ?>&amp;cd[currency]=<?php echo $currency_code ?>&amp;noscript=1" /></noscript>
