<?php 
     $enable = $this->getEnable();
     $custom = $this->getCustom();
     if (!$enable) {
         return;
     }
     $id = $this->getPixelId();
     $currency_code = $this->getCurrencyCode();
     $grand_total = round($this->getOrderTotal(), 2);
    if(!$custom){ ?>
		<!-- Facebook Pixel Code -->
		<script>
		!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
		n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
		n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
		t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
		document,'script','//connect.facebook.net/en_US/fbevents.js');
		// Insert Your Facebook Pixel ID below. 
		fbq('init', '<?php echo $id ?>');
		fbq('track', 'PageView');
		</script>
		<!-- Insert Your Facebook Pixel ID below. --> 
		<noscript><img height="1" width="1" style="display:none"
		src="https://www.facebook.com/tr?id=<?php echo $id ?>&ev=PageView&noscript=1"
		/></noscript>
		<!-- End Facebook Pixel Code -->
   <?php }else{ ?>
		<!-- Facebook Conversion Code for Conversions -->
		<script>(function() {
			var _fbq = window._fbq || (window._fbq = []);
			if (!_fbq.loaded) {
			    var fbds = document.createElement('script');
			    fbds.async = true;
			    fbds.src = '//connect.facebook.net/en_US/fbds.js';
			    var s = document.getElementsByTagName('script')[0];
			    s.parentNode.insertBefore(fbds, s);
			    _fbq.loaded = true;
			}
		    })();
		    window._fbq = window._fbq || [];
		    window._fbq.push(['track', '<?php echo $id ?>', {'value':'<?php echo $grand_total ?>','currency':'<?php echo $currency_code ?>'}]);
		</script>
		<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?ev=<?php echo $id ?>&amp;cd[value]=<?php echo $grand_total ?>&amp;cd[currency]=<?php echo $currency_code ?>&amp;noscript=1" /></noscript>
<?php } ?>
