<?php
/**
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @copyright   Copyright (c) 2015 Weboffice UG (haftungsbeschränkt) (http://www.Weboffice.de)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php echo $this->getCaptchaHtml() ?>

<?php echo $this->getStoreSwitcherHtml() ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"></div>
        <h4 class="fieldset-legend"><?php echo $this->__('Google Content Items') ?></h4>
    </div>
    <?php echo $this->getChildHtml('item') ?>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"><?php echo $this->getAddButtonHtml() ?></div>
        <h4 class="fieldset-legend"><?php echo $this->__('Available Products') ?></h4>
    </div>
    <?php echo $this->getChildHtml('product') ?>
</div>

<script type="text/javascript">
//<![CDATA[
Mage.GoogleShopping.isProcessRunning = <?php echo $this->isProcessRunning() ? 'true' : 'false'; ?>;
Mage.GoogleShopping.statusUrl = '<?php echo $this->getStatusUrl(); ?>';
Mage.GoogleShopping.runningMessage = '<?php echo $this->__('Google Shopping synchronization process is running');?>';
//]]>
</script>
