<?php 
$iStore = Mage::app()->getStore()->getId();
?>
<?php
$productId = $this->getProductID();
$Popularity = Mage::getModel('popularity/popularity');
$popularity = $Popularity->getPopularity($productId,$iStore);
$sell = Mage::helper('popularity')->getSell($iStore);
$rating = Mage::helper('popularity')->getRating($iStore);
$view = Mage::helper('popularity')->getViews($iStore);
$design = Mage::helper('popularity')->getDesign($iStore);
$step = Mage::helper('popularity')->getStep($iStore);
if($step == NULL)$step = 250;
$pop = array_sum($popularity);

?>
 <ul class="downloads-reviews clearfix">
   <li class="downloads">
                       <?php $stepsimg = 0;for($x=1;$x<=5;$x++){
		              if($x == 1){
		                  if($pop == 0) $src = $this->getSkinUrl('images/popularity').DS.$design.DS.'icon'.$x.'.png';
		              }elseif($x == 2){
		                   if($pop > 0 && $pop <= $step) $src = $this->getSkinUrl('images/popularity').DS.$design.DS.'icon'.$x.'.png';
		              }else{
		                   $stepsimg = $stepsimg+$step; 
		                   if(($pop > $step) && ($pop >= $stepsimg+1 && $pop <= $stepsimg+$step)) $src = $this->getSkinUrl('images/popularity').DS.$design.DS.'icon'.$x.'.png';
		                     
		              } 
                 	} ?>    
       <strong>
                <img src="<?php echo $src; ?>" alt="Popularity Score">
                 <?php echo $pop; ?> <?php echo $this->__('Popularity Score');?>                
        </strong>
       <div id="downloads-reviews-popularity-score-box" class="ui-tooltip" style="top: 135%; ">
    		<p class="first">
                       <strong><?php echo $this->__('Popularity Score');?></strong>
                       <?php echo $this->__('Referrals to Site\'s');?>
                       <?php if($sell):?>
                        <?php echo $this->__('/ Sales(%d)', (int)$popularity['sales']); ?>
                       <?php endif; ?>
		       <?php if($view):?>
                        <?php echo $this->__('/ Views(%d)', (int)$popularity['views']); ?> 
		        <?php endif; ?>
		       <?php if($rating):?>
                         <?php echo $this->__('/ Reviews(%d)', (int)$popularity['reviews']); ?>
                       <?php endif; ?>
                      </p>

    <p class="last">                                                
           
            <?php $steps = 0;for($i=1;$i<=5;$i++): ?>
                      <?php if($i == 1): ?>
                         <span class="<?php if($pop == 0) echo 'active';?>">
                              <img src="<?php echo $this->getSkinUrl('images/popularity').DS.$design; ?>/icon<?php echo $i;?>.png" alt="0" width="21" height="20">
                              0            
                         </span>
                      <?php elseif($i == 2): ?>
                         <span class="<?php if($pop > 0 && $pop <= $step) echo 'active';?>">
                           <img src="<?php echo $this->getSkinUrl('images/popularity').DS.$design; ?>/icon<?php echo $i;?>.png" alt="1+" width="21" height="20">
                            1+            
                          </span>
                      <?php else: ?>
                            <?php $steps = $steps+$step; ?>
                            <span class="<?php if(($pop > $step) && ($pop >= $steps+1 && $pop <= $steps+$step)) echo 'active';?>">
                             <img src="<?php echo $this->getSkinUrl('images/popularity').DS.$design; ?>/icon<?php echo $i;?>.png" alt="<?php echo $steps;?>+" width="21" height="20">
                              <?php echo $steps;?>+            
                          </span> 
                         <?php //break; ?> 
                      <?php endif; ?>
             <?php endfor; ?>    
     </p>
     </div>
            </li>
</ul>

